puppylinux-woof-CE/gtkdialog

- doc/reference/terminal.html
- examples/terminal/terminal
- src/automaton.c
- src/widget_terminal.c
Had to remove support for "background-tint-color" and
"dim-foreground-color" because these were removed in vte 0.38
I do not claim to understand why vte-2.91.pc = Version: 0.48.4
Running './configure --enable-gtk3'
requires a newer version of vte than the default in Artful.
Running the following commands first will force using vte-2.91
export VTE_CFLAGS=`pkg-config --cflags "vte-2.91"`
export VTE_LIBS=`pkg-config --libs "vte-2.91"`
Should fix #50
> Fixes for gtk+3 / vte-2.91

- src/automaton.c
Only needed for vte-0-38 and newer (gtk+3), so gtk+2 builds should be back to using the old vte_terminal_get_padding function now.
> Use gtk_style_context_get_padding instead of "inner-border" property

- src/gtkdialog.c
- src/gtkdialog.h
Same problem as https://github.com/wjaguar/mtPaint/issues/46
> Fix build failure against GCC 10 due to redefined globals

- configure.ac
- src/automaton.c
Now configure should be able to automatically find the correct
versions of VTE for GTK3.
Also changed automaton.c to use gtk_style_context_get_padding()
for all GTK3 based builds.
> Improve building with GTK3 and VTE

- src/automaton.c
This function calls `gtk_widget_set_uposition()`, which is missing from GTK+ 3. Release builds against GTK+ 3 work, because this unresolved symbol is referenced by an unused function.
> Remove widget_moved() from GTK+ 3 builds

- .github/workflows/build.yml
- README
- meson.build
- meson_options.txt
- src/meson.build
- src/widget_window.c
- subprojects/gtk-layer-shell.wrap
To see it in action: add `layer="overlay"` to the `<window>` tag of /usr/lib/gtkdialog/box_splash.
This change is backward-compatible - current gtkdialog releases ignore this new attribute.
> Add layer shell support

- src/widget_window.c
This adds ability to place gtkdialog programs on the wayland screen at topleft, top, topright, right, bottomright, bottom, bottomleft and left.
> Add gtk_layer_set_anchor support to widget_window.c re #101

- doc/reference/edit.html
- doc/reference/text.html
- examples/edit/edit_attributes
- examples/edit/edit_scrolling
- examples/text/text_scrolling
- src/Makefile.am
- src/automaton.c
- src/meson.build
- src/scrolling.c
- src/scrolling.h
- src/widget_edit.c
- src/widget_text.c
This commit extends the custom attributes of text and edit widgets to
allow scrolling their content to the bottom when the widget is refreshed.
This allows "following" content updates if the widget is set to
auto-refresh - sort of like tail -f does.
Since the edit widget is scrollable by definition, just the new
scroll-to-bottom="true" custom attribute suffices to set the widget to
scroll on refresh.
The text widget takes on this new attribute, as well as the same group
of "scrolling" attributes that the vbox and hbox widgets define for
themselves.
The edit widget doesn't support pango markdown but the text widget does.
To see this new feature in action run the included example scripts.
Documentation updated. Note that I set the generic label "0.8.4+" as
the inception version of this …
> feature: scroll edit and text widgets to bottom on refresh

- src/signals.c
- src/signals.h
- src/variables.c
- src/variables.h
This PR replaces #116.
This commit extends the signal handling code involved with "auto-refresh" and "file-monitor" custom attributes to make it compile and work with GTK+-3.
It also fixes several "implicit declaration" compiler warnings.
The following scripts are simple and effective tests for auto-refresh and file-monitor because they set up 100 watches. Make sure to test all eight combinations: {gtk2, gtk3} x {w/, w/o inotify} x {auto-refresh, file-monitor}:
- examples/pixmap/pixmap_auto_refresh
- examples/pixmap/pixmap_file_monitor
> extend inotify-based signals for gtk3

- doc/reference/chooser.html
- examples/chooser/chooser
- examples/chooser/chooser_deprecated
- examples/chooser/chooser_event_counters
- examples/chooser/chooser_file_filters
- examples/chooser/chooser_in_out
- src/Makefile.am
- src/automaton.c
- src/meson.build
- src/signals.c
- src/signals.h
- src/variables.c
- src/widget_chooser.c
- src/widget_chooser.h
- src/widgets.c
The file chooser widget has been included in gtkdialog since the early
days but was shadowed by the chooser dialog, which can be invoked with
the `fileselect` function.  Consequently, Thunor didn't give the chooser
widget the kind of feature uplift that was given to other widgets, and
moved the chooser widget to the miscellaneous example folder, where it
can still be found today.
However, for a specific class of applications - file viewer such as
mm_view and desktop wallpaper setters - the file chooser can be very
valuable: it is the only widget that allows embedding a full file
browser in a larger dialog.  The trouble was that the existing
implementation was not on par with the rest of gtkdialog.  This commit
fixes that and elevates the chooser widget to full citizenship. May
application …
> feature: new chooser widget

- examples/miscellaneous/conditional_actions_2022
- src/signals.c
Introducing signal condition "variable_is_true"
Before it executes an action with signal condition "variable_is_true",
any widget can test the truth value of another widget directly, that is,
without needing a backing file or a shell command to get the truth value.
See examples/miscellaneous/conditional_actions_2022 for details.
Motivation for adding variable_is_true: scripts run faster because
they perform less I/O or spawn fewer shell commands.  Note that
variable_is_true isn't strictly necessary; it doesn't do anything that
couldn't be done with file_is_true or command_is_true - but it does
it more simply and lightly than those two.
> feature: signal action variable_is_true

- examples/chooser/chooser_event_counters
- src/signals.c
- src/signals.h
- src/widget_chooser.c
Now I'm satisfied with the way the chooser widget works in GTK3 and GTK2 for all practical purposes.  Two minor quirks remain:
* On signal `current-folder-changed` the `<variable>` value matches the currently selected folder only if the user has selected and entered that folder.  There are no clear rules for deriving the value otherwise. (GTK2 and GTK3)
* When `fs-filters` or `fs-filters-mime` are defined, at times the `<variable>` value that results from the user filtering the file list does not match the selection. (GTK3)
> improve chooser widget

- src/gtkdialog_lexer.l
This is to fix one of my pet peeves with gtkdialog, that is, inside `<action>` and `<input>` tags the shell input redirection operator `<` triggers a syntax error and aborts gtkdialog.
Traditionally this limitation is worked around with shell pipes or temporary files. Take for example an action that aims at printing the line count of `/etc/passwd` as a bare number without further text. This command would do `wc -l < /etc/passwd` but when gtkdialog sees the command, e.g. `<action>wc -l < /etc/passwd</action>`, it prints "gtkdialog: Error in line 1, near token 'string': syntax error" and exits. So we must rewrite the command as `<action>cat /etc/passwd | wc -l</action>`, which forks an additional process. Enter this commit. Now shell input redirection is valid syntax, and gtkdialog keeps …
> Allow shell input redirection `< /file` in action and input tags

- src/automaton.c
- src/signals.c
- src/variables.c
- src/variables.h
Function `variables_is_avail_by_name` is redundant so I decided to retire it because it obscures when malloc
did take place.  I didn't write new functions to replace it - I just reused existing functions consistently.
`variables_is_avail_by_name` is retired in favor of two simpler idioms:
```c
/* create */
var = variables_get_by_name(name); /* perform look-up */
if (var == NULL)
var = variables_new(name); /* malloc */
/* use */
var = variables_get_by_name(name); /* perform look-up */
if (var != NULL) {
/* use var */
}
```
> simplify file variables.c

- examples/miscellaneous/comments.sh
- src/gtkdialog_lexer.l
This commit adds XML-style comments as a lexical feature that script
developers can use to easily document their code. It also fixes two
long-standing bugs: the line counter that references the location of
a syntax error did not count multi-line values; markup `<edit ` was
incorrectly reported as an `<entry>` token (with no ill consequences).
Prior to this commit the gtkdialog markup did not provide a native way
to enter comments. Several work-arounds were in use: side-loading
comments in a separate file; writing shell comments at the top/bottom/
middle of the shell script file; embedding shell comments in gtkdialog
markup using various ad-hoc (and fragile) lexical hacks; using a shell
function to create an envelope for comments; forking an `<action>` that
runs nothing but shell comments. …
> lexer: add XML-style comments and fix line counter

- src/gtkdialog_lexer.l
Test case `gtkdialog -c -s <<< $'<button></button>'`.
Complements #129.
> accept empty XML comment

- doc/reference/window.html
- src/widget_window.c
This allows the use of a gtk theme icon for the window/taskbar icon.
It works in gtk2 and gtk3. It is useful if you add a theme icon
(can and should be in the 'hicolor' theme) for your app.
This is needed for wayland support (eg sfwbar can now display
appropriate icons instead of the default) however the old
method of 'image-name' doesn't work in wayland because 'app_id'
is needed. This is why there is a call to `g_set_prgname()`
> new window attr: 'icon-name'

- data/meson.build
- meson.build
Simply, the icon wasn't installed with meson  and the window manager / taskbar
was showing whatever it's fallback icon was.
> meson: fix installation of gtkdialog.png icon

- .github/workflows/build.yml
This will ensure `ninja install` and `make install` don't break.
> Add an installation step to the CI flow

- src/widget_window.c
- no need for an attr in the top-level widget
- this works again now
`gtkdialog -s <<< '<button ok></button>'`
> widget_window.c: bugfix for regression in 262be11

- doc/meson.build
- meson.build
- meson_options.txt
- adds documentation and examples if `-Ddocs=true`
- disabled if not explicitly set as 'true' on meson command line
> meson: add docs to install; default is false

- .github/workflows/build.yml
- meson.build
- src/meson.build
gtk-layer-shell is sensitive to the GTK+ version, and the system-provided one is more likely to work.
> Use system-provided gtk-layer-shell if possible

- meson.build
- src/meson.build
8ab7b64 makes gtk-layer-shell a mandatory dependency.
It looks like some older Puppies have some Wayland development packages, because they're dependencies of GTK+ 3's development packages, but not all of them. The dependency chain is broken.
In particular, libwayland-bin is missing and assumed to be installed, so /usr/bin/wayland-scanner is missing and the gtk-layer-shell must be disabled to prevent build failure.
People will complain they can't build the latest gtkdialog, so let's keep the subproject fallback, but disable gtk-layer-shell support completely if the subproject has missing dependencies.
> Fix build failure if wayland-scanner is missing

- src/widget_window.c
- subprojects/gtk-layer-shell.wrap
Before programs such as `yaf-spalsh, gtkdialog-splash` were pushing widows out of the way in wayland. That shouldn't happen.
Also bumped `gtk-layer-shell` version to 'latest stable'
> fix exclusive zone, bump gtk-layer-shell version

- .github/workflows/build.yml
- meson_options.txt
- src/actions.c
- src/meson.build
/bin/sh is bash in Puppy, but not in all distros. I want to switch to dash as /bin/sh in dpup, to avoid the overhead of bash.
However, some gtkdialog-based tools assume that the shell is bash (for example, they use `export -f` and call the exported functions via `<action>`) and things "just work" because system() runs `sh -c`.
This PR adds a built option, `-Dbash=true`, which makes gtkdialog run commands via `bash -c` instead of `sh -c`.
> Add build option to run commands via bash -c
